site_name: Uso de Datos Abiertos de la Junta de Castilla y León en Desarrollo Web
strict: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist


# Estructura de navegación
nav:
  - '🏠 Inicio': 'index.md'
  - '🔎 Buscador con IA': 'buscador-ia.md'
  - '0️⃣ Introducción 🚀':
    - '0.1 Introducción a los Datos Abiertos': '0-presentacion/0-1-introduccion-datos-abiertos.md'
    - '0.2 Gobierno abierto, transparencia y participación': '0-presentacion/0-2-gobierno-abierto.md'
    - '0.3 Tipos de datos abiertos y formas de acceso': '0-presentacion/0-3-tipos-datos.md'
  - '1️⃣ Fundamentos de Fetch, promesas y async/await':
    - '1.1 Lección': '1-fetch/1-1-fetch-leccion.md'
    - '1.2 Ejemplo con JavaScript puro (vanilla)': '1-fetch/1-2-fetch-ejemplo-vanilla.md'
#    - '1.3 Ejemplo con librería (Axios)': '1-fetch/1-3-fetch-ejemplo-libreria.md'
#    - '1.4 Demo: Agenda cultural (API REST)': '1-fetch/1-4-fetch-demo.md'
  - '2️⃣ CSV 📃':
    - '2.1 Lección': '2-csv/2-1-csv-leccion.md'
    - '2.2 Ej. CSV con Vanilla JS': '2-csv/2-2-csv-ejemplo-vanilla.md' 
    - '2.3 Ej. Librerías Papa Parse + Tabulator': '2-csv/2-3-csv-ejemplo-libreria.md'
    - '2.4 Demo: Hostelería a domicilio (CSV)': '2-csv/2-4-csv-demo.md'
  - '3️⃣ XML 📃':
    - '3.1 Lección': '3-xml/3-1-xml-leccion.md'
    - '3.2 Ej. XML con JS puro': '3-xml/3-2-xml-ejemplo-vanilla.md'
    - '3.3. Ej. Librería fast-xml-parser': '3-xml/3-3-xml-ejemplo-libreria.md'
    - '3.4 Demo: Agenda cultural (XML)': '3-xml/3-4-xml-demo.md'
  - '4️⃣ JSON 📃':
    - '4.1 Lección': '4-json/4-1-json-leccion.md'
    - '4.2 Ej. JSON con JS puro': '4-json/4-2-json-ejemplo-vanilla.md'
    - '4.3 Ej. Librería Axios': '4-json/4-3-json-ejemplo-libreria.md'
    - '4.4 Demo: Instituciones bibliotecarias (JSON)': '4-json/4-4-json-demo.md'
  - '5️⃣ API 📃':
    - '5.1 Lección': '5-api/5-1-api-leccion.md'
    - '5.2 Ej. API con JS puro': '5-api/5-2-api-ejemplo-vanilla.md'
    - '5.3 Ej. Librería Axios': '5-api/5-3-api-ejemplo-libreria.md'
    - '5.4 Demo: Agenda cultural (API REST)': '5-api/5-4-api-demo.md'
  - '6️⃣ Tablas ⊞':
    - '6.1 Tablas': '6-tablas/6-1-tablas-leccion.md'
    - '6.2 Ej. Tablas con JS puro': '6-tablas/6-2-tablas-ejemplo-vanilla.md'
    - '6.3 Ej. Librería Tabulator': '6-tablas/6-3-tablas-ejemplo-libreria.md'
    - '6.4 Demo: Estadísticas de redes sociales (CSV)': '6-tablas/6-4-tablas-demo.md'
  - '7️⃣ Gráficos 📈':
    - '7.1 Gráficos': '7-graficos/7-1-graficos-leccion.md'
    - '7.2 Ej. Gráficos con JS puro': '7-graficos/7-2-graficos-ejemplo-vanilla.md'
    - '7.3 Ej. Librería Chart.js': '7-graficos/7-3-graficos-ejemplo-libreria.md'
    - '7.4 Demo: Estadísticas de redes sociales (CSV)': '7-graficos/7-4-graficos-demo.md'
  - '8️⃣ Mapas 🗺️':
    - '8.1 Mapas': '8-mapas/8-1-mapas-leccion.md'
    - '8.2 Ej. Mapas con JS puro': '8-mapas/8-2-mapas-ejemplo-vanilla.md'
    - '8.3 Ej. Librería Leaflet': '8-mapas/8-3-mapas-ejemplo-libreria.md'
    - '8.4 Demo: Centros docentes (CSV)': '8-mapas/8-4-mapas-demo.md'


# Configuración del tema
theme:
  name: material
  language: es
  custom_dir: overrides
  logo: assets/images/logo.png
  
  # Características
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - header.autohide
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs.linked
  
  # Navegación
  navigation:
    collapse: true
    sticky: true
    
  # Paleta de colores
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a tema oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a tema claro

# Configuración de búsqueda
plugins:
  - search:
      separator: '[\s\-:]+'
      lang: 'es'

# Configuración de la página
use_directory_urls: true

# CSS personalizado
extra_css:
  - https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;600&display=swap
  - jcyl.css

# Footer personalizado
extra:
  copyright: "&copy; 2025 Laura Folgado Galache - laurafolgadogalache@gmail.com"
